### ISSUE TITLE
Domains with dashs - do not work

### ISSUE THREAD

**Issue by lrissman-github** [aanousakis/no-ip#1]
No-ip supports domain names with dashes.   Eg:   abc-def.ddns.net

Your script strips dashes when discovering the domain name and then never matches domains similar to the above example.  

script.exp
lines 105-107

https://github.com/aanousakis/no-ip/blob/1b4a21266007fc5fe6bad81fd7871fab6c1d43f5/scripts/script.exp#L106

  expect {
    -re {([a-zA-Z0-9]*\.)*[a-zA-Z0-9]*} { set check_domain $expect_out(0,string); puts "$check_domain"}
  }

**Comment by aanousakis** [comment]
Hi, changing the regular expression to -re {([a-zA-Z0-9\-]*\.)*[a-zA-Z0-9]*} should work. Thank you.

**Comment by lrissman-github** [comment]
Thank you for the quick response.   I see you updated github and published the amd64 image on hub.docker.   I'll test as soon as the 64-bit arm images are published.

**Comment by lrissman-github** [comment]
I got impatient and built the container on my arm64 device and updated my image.     Added a test domain and it is working properly.    Thank you again.


```
Do you wish to have host [test-abc.ddns.net] updated?[N] (y/N)  test-abc.ddns.net,
y
```
