### ISSUE TITLE
Latest release seems to freeze at spawn noip2 and causes 100% CPU utilization

### ISSUE THREAD

**Issue by idimou** [aanousakis/no-ip#1]
Hi, 
first of all thanks for the cool utility. 
There seems to be a problem with the latest image:
The previous image: 
aanousakis/no-ip@sha256:3783fd7162b35de1ca8257b9fe22776ddfc0db88ab78f2de8b80fb1230d37876
seems to work fine.
The latest one:
aanousakis/no-ip@sha256:011ad8c54e8f597da8c297400c841a48b41cebd0fb75a4a1771464590ccd71e9
not.

Container log:
Check and import env variables
Checking filename env variables
Secret filenames doesn't exist
Checking if env variables exist
env variables exist
Starting process to generate config file
***********************************
**         Configuration         **
***********************************
username ######
password ############
domains #######
interval 5
Found 1 adapters
spawn noip2 -C

**Comment by aanousakis** [comment]
The latest alpine update causes the problem if you have 32-bit cpu. For a quick fix you could try an older alpine version. It will take me a few days create a new tag and reupload.

**Comment by idimou** [comment]
Indeed this was on an arm32. Switched to a previous version as a workaround, thanks. Grateful if you can fix this also. 

/ / Ioannis

**Comment by aanousakis** [comment]
I created a new tag 1.0 which use alpine:1.12. If you want to use the latest alpine version you have to [manually update libseccomp ](https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-812287338)
