### ISSUE TITLE
Unable to get it working on raspberry pi 3b with casaOS

### ISSUE THREAD

**Issue by chuyrg** [aanousakis/no-ip#5]
I just tried to make this one work, since the other no-ip clients i've tested doesn't work for the arm architecture, when i import the docker CLI command to casaOS, it installs without any issues, but when it tries to run, i get the following in the console:

Check and import env variables
Checking filename env variables
Secret filenames doesn't exist
Checking if env variables exist
env variables exist
Starting process to generate config file
***********************************
**         Configuration         **
***********************************
username xxx
password xxx
domains xxx.hopto.org
interval 5
Found 1 adapters
spawn noip2 -C -c /config/no-ip2.conf

Auto configuration for Linux client of no-ip.com.

Can't gethostbyname for dynupdate.no-ip.com
Network must be operational to create configfile. Ending!
expect: spawn id exp3 not open
    while executing
"expect -exact "$username\r\nPlease enter the password for user '$username'  "   {send -- "$password\r" }"
    (file "./script.exp" line 154)
Failed to start noip2 -C : 1

**Comment by aanousakis** [comment]
I don't see something obvious, so you will have to try a few things.

- Open a shell inside the container 
`docker run -it --entrypoint /bin/sh aanousakis/no-ip`

- Test the internet connection inside the container
`ping google.com`

- Create the configuration manually
`noip2 -C -c /config/no-ip2.conf`

From the log above i assume there is a problem with the network. Finally an alpine update caused network problems and high cpu usage, so try the older version `aanousakis/no-ip:3.12` .

**Comment by chuyrg** [comment]
> I don't see something obvious, so you will have to try a few things.
> 
>     * Open a shell inside the container
>       `docker run -it --entrypoint /bin/sh aanousakis/no-ip`
> 
>     * Test the internet connection inside the container
>       `ping google.com`
> 
>     * Create the configuration manually
>       `noip2 -C -c /config/no-ip2.conf`
> 
> 
> From the log above i assume there is a problem with the network. Finally an alpine update caused network problems and high cpu usage, so try the older version `aanousakis/no-ip:3.12` .

Yeah, it was a connection issue, i switched the network from bridged to host in casaOS and it connected to noip, i also downgraded to the 3.12 version as you suggested, thanks!
